### ISSUE TITLE
Start hue service [fail]

### ISSUE THREAD

**Issue by holl59** [caioquirino/docker-cloudera-quickstart#10]
Hi,

When, I start the container, the hue service [fail].

idem, if i stop / start the service 

In /var/log/hue/error.log, i have :

`[23/Apr/2015 08:13:39 ] supervisor   ERROR    Exception in supervisor main loop
Traceback (most recent call last):
  File "/usr/lib/hue/desktop/core/src/desktop/supervisor.py", line 386, in main
    wait_loop(sups, options)
  File "/usr/lib/hue/desktop/core/src/desktop/supervisor.py", line 396, in wait_
loop
    time.sleep(1)
  File "/usr/lib/hue/desktop/core/src/desktop/supervisor.py", line 218, in sig_h
andler
    raise SystemExit("Signal %d received. Exiting" % signum)
SystemExit: Signal 15 received. Exiting
`

Any idea ?

Regards

**Comment by holl59** [comment]
Nobody here ?

**Comment by rafadaguiar** [comment]
I'm having the same issue.

**Comment by caioquirino** [comment]
Hi people, sorry for the delay. Are you still having this issue?

**Comment by holl59** [comment]
Hi,
The error wasn't really clear... the problem came from not enough memory
