### ISSUE TITLE
Hue username and password

### ISSUE THREAD

**Issue by petchadj** [caioquirino/docker-cloudera-quickstart#16]
What's the Hue username and password? Thanks in advance!

**Comment by butterhc** [comment]
It should be hue:hue

**Comment by sventenscher** [comment]
try hdfs:hdfs , based on the quickstart guide from Cloudera (also possible cloudera:cloudera , based on an intro video about the Cloudera VM)

**Comment by petchadj** [comment]
No luck. I'm gonna give the official cloudera/quickstart docker image a try. Just released yesterday!  

https://hub.docker.com/r/cloudera/quickstart/

**Comment by Sergic** [comment]
admin:admin

**Comment by caioquirino** [comment]
For the first time you use the image you will define the admin username and password. Please login and define before.
Did it works with you?
